version: '3.8'

services:
  videolingo:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./output:/app/output
      - ./custom_terms.xlsx:/app/custom_terms.xlsx
      - ./_model_cache:/app/_model_cache
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    stdin_open: true
    tty: true 